
O que é o numpy?


Biblioteca para armazenar vetores de n dimensões e realizar operações matemáticas
sobre essas estruturas de dados

numpy x listas

As listas python são mais lentas que arrays numpy.

Aplicações do numpy

* Computação científica.
* Machine learning

Numpy é mais rapido porque:
    1) Os tipos são fixos no numpy, enquanto que no python cada item pode ter um
    tipo diferentes. Vamos analisar um tipo inteiro: para o numpy, o tipo inteiro
    é aquele classicão de c: vc tem uma quantidade de bits e só isso é armazenado

    Para python, o tipo number possui uns 4 campos, e cada campo é um long.
    Então no fim do dia, cada item numa lista ocupa mais espaço que itens no numpy.
    Assim, o numpy lê e escreve mais rapida

    2) Numpy usa memória contigua: listas em  python na verdade são listas ligadas,
    então a leitura de uma lista de tamanho n é O(n). Em numpy, é O(1).


Diferenças entre os dois: o numpy é um superset das listas: ele faz tudo que uma 
lista faz, mas um pouco mais: um exemplo é multiplicação de vetores:

In [36]:
import numpy as np

a = np.array([1,3,5]) # inicialização de um objeto numpy
b = np.array([1,2,3])
c = a * b
print(c) # A operação de multiplicação não vem implementada out of the box para lists

[ 1  6 15]


In [37]:

a = np.array([[1,2,3,4,5,6,7], [8,9,10, 11,12,13,14]]) # 2x7
print(a[1,3])

# Pegar uma coluna especifica:

print(a[0, :])

# Pegar elementos partindo de um indice inicial até um indice final, e especificando
# os passos

print(a[0, 1:6:2]) #Pegue a primeira linha. Então, acesse os elementos correspondentes partindo do indice 1 até o indice 6, dando passos de 2 em 2.

# escrita:

a[0,0] = 1
print(a)
a[:, 2] = [1,3]
print(a)


11
[1 2 3 4 5 6 7]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  3 11 12 13 14]]


Se quisermos trabalhar com arrays em 3d, é similar:

In [38]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
# Pegar elemento específico: vamos trabalhar de fora pra dentro:

b[0,1,1]# Pegue um elemento do primeiro vetor. Nesse vetor,
    #vamos selecionar o segundo vetor. Nesse segundo vetor, pegue o
    # segundo item

4

Para atribuição é a mesma coisa, basta garantir que estamos trabalhando nas mesmas dimensões.


## inicializando diferentes tipos de array

In [40]:
# Todos 0s

zeros = np.zeros((2,3,5)) #aceita um shape

print(zeros)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [41]:
# Todos 1s

ones = np.ones((5,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [42]:
# Com qualquer número

full = np.full((2,2), 9) # Aceita um shape e um valor inicial
print(full)

[[9 9]
 [9 9]]


In [43]:
# preencher array ja existente com algum valor

reciclado = np.full_like(a, 4)
print(reciclado)

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [44]:
# Numeros aleatorios (util pra SGD)

rnd = np.random.rand(4,2) #api estranha.
print(rnd)

[[0.32962478 0.20429941]
 [0.89411968 0.73551668]
 [0.67447886 0.73013566]
 [0.78694123 0.42943883]]


In [45]:
# Com inteiros aleatorios
# Passa o inteiro inicial e final
np.random.randint(7, size=(3,3))
#api estranha again: isso é um shape, não um size

array([[2, 3, 4],
       [3, 1, 6],
       [6, 4, 0]])

 ## Matemática no np

No np, podemos realizar operações de algebra linear tranquilamete, com algumas facilitações

In [47]:
# Se quisermos somar 2 elementos na matriz inteira, na algebra linear
# fariamos isso:

a = np.array([1,2,3])
b = np.full(3,2)
print(a+b)

# Mas o numpy tem um atalho pra isso

print(a + 2)

# E isso vale pra toda operação. O numpy faz a operação element-wise:

print(a * 10)
a**2

[3 4 5]
[3 4 5]
[10 20 30]


array([1, 4, 9])

## Algebra linear no np

In [52]:
# Multiplicação

a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)
# Fazer a * b não funciona, o np espera dois elementos com mesmo tamanho
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [53]:
# Determinante
c = np.identity(3)
np.linalg.det(c)

1.0

## Estatística no np

In [55]:
stats = np.array([[1,2,3], [4,5,6]])

In [56]:
np.max(stats)

6

In [57]:
np.min(stats) 

1

In [58]:
np.sum(stats)

21

## Reorganizando arrays

In [61]:
antes = np.array([[1,2,3,4], [5,6,7,8]])
print(antes.shape)
print(antes)
# Transforma em um 8x1

depois = antes.reshape((8,1)) #AS novas dimensoes devem ser multiplas da orignial
print(depois)
 print(depois.shape)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


## Transformando e indexando com booleanos

In [68]:
# Podemos usar valores booleanos para transformar nosso aray:

rand = np.random.rand(2,3) * 100
rand_novo  = rand > 50
print(rand_novo) # mostre aonde é verdadeiro
print(rand[rand > 50]) # Mostre os itens aonde a condição é verdadeira

[[False  True  True]
 [False  True  True]]
[59.29722437 60.57038181 50.94321746 52.43768203]


## Indexando com listas

In [69]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # Pegue os itens com esses indices

array([2, 3, 9])

### Exercicios

In [82]:
p = np.array([[1,2,3,4,5],\
               [6,7,8,9,10],\
               [11,12,13,14,15],\
               [16,17,18,19,20],\
               [21,22,23,24,25],\
               [26,27,28,29,30]])
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [83]:
p[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [86]:
p[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [113]:
p[[0,-2,-1], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [112]:
p[[0,-2,-1], [0, 1, 0]]

array([ 1, 22, 26])